services:
  chall:
    image: superwebsiteverificator:latest
    build: .
    ports:
      - "5000:80"
    environment:
      - LISTEN_PORT=80
      - INTERNAL_PORT=600
      - FLAG=HACKDAY{Give_ME_YOuR_L0OPb@CK}
